[BROKEN?] Suppress config.parse_time exc chaining
In python3, raising exceptions from an except block cause a chained
traceback to be printed; eg.

        Traceback (most recent call last):
          File "<stdin>", line 2, in <module>
        NameError: name 'asdf' is not defined

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "<stdin>", line 4, in <module>
        ValueError

This commit suppresses the chaining of config.InvalidTime exceptions
from the caught TypeError / ValueError.