Fix JSONDecodeError from instagram /media endpoint
The /media endpoint will sometimes return bad json. I'm not sure why but
this commit assumes that it is a temporary issue and will retry up 10
times, re-raising the error if too many retries have been attempted. It
currently waits a hard-coded 5s before every retry attempt.

This commit also enqueues the instagram user's state when re-raising
fatal errors.

-----
The following is a snippet of the traceback:

  File "src/instagram.py", line 534, in __fetch_data
    url=response.url,
  File "~/.local/lib/python3.5/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 69152 (char 69151)