Fix praw stream request timeout
This broadens StreamMixin's class of retryable exceptions to include ALL
RequestExceptions since they should always be client-side,
non-programming related errors (ie, they should always be retryable).

I've commented out the errno==ECONNRESET code in case I want to narrow
the set of retryable exceptions later.

The following is the timeout error thrown by prawcore:

prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16.0)